- hosts: localhost
  tasks:
    - name: remove neovim
      shell: rm -rf ~/build/neovim
    - name: get packer
      ansible.builtin.git:
        repo: "https://github.com/wbthomason/packer.nvim"
        dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    - name: clone neovim
      ansible.builtin.git:
        repo: "https://github.com/neovim/neovim.git"
        dest: "{{lookup('env', 'HOME')}}/build/neovim"
    - name: build neovim
      shell: "cd {{lookup('env', 'HOME')}}/build/neovim && make -j 20"
    - name: install neovim
      shell: "cd {{lookup('env', 'HOME')}}/build/neovim && make install"
